Fixed boost installation so that it compiles with C++11. Otherwise, newer compiler versions fail with errors like
```
./boost/container_hash/hash.hpp:132:33: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
```

Also, we have to add the CXX flag -Wno-enum-constexpr-conversion for boost comiplation otherwise we get the following error:

```
./boost/mpl/aux_/integral_wrapper.hpp:73:31: error: integer value -1 is outside the valid range of values [0, 3] for the enumeration type 'int_float_mixture_enum' [-Wenum-constexpr-conversion]
```